name: Selenium Framework Development Workflow

phases:
  setup:
    description: "Initial project setup and configuration"
    tasks:
      - create_project_structure
      - setup_maven_configuration
      - create_base_directories

  core_framework:
    description: "Core framework components"
    depends_on: setup
    tasks:
      - webdriver_management
      - base_classes
      - configuration_management
      - utility_classes

  page_objects:
    description: "Page Object Model implementation"
    depends_on: core_framework
    tasks:
      - analyze_application
      - create_page_objects
      - implement_locators
      - add_page_actions

  test_data:
    description: "Test data management setup"
    depends_on: core_framework
    tasks:
      - setup_data_factories
      - create_test_data_files
      - implement_data_utilities

  test_implementation:
    description: "Test case creation"
    depends_on: [page_objects, test_data]
    tasks:
      - create_base_tests
      - implement_test_scenarios
      - setup_testng_configuration

  reporting:
    description: "Reporting and logging setup"
    depends_on: core_framework
    tasks:
      - configure_extent_reports
      - setup_allure_reporting
      - implement_logging
      - add_screenshot_utilities

  ci_cd:
    description: "CI/CD configuration"
    depends_on: [test_implementation, reporting]
    tasks:
      - create_github_actions
      - setup_docker_configuration
      - create_jenkins_pipeline

agent_assignments:
  framework_architect:
    phases: [setup, core_framework]
    coordination: true

  page_object_creator:
    phases: [page_objects]

  test_data_manager:
    phases: [test_data]

  config_manager:
    phases: [setup, core_framework]

  test_creator:
    phases: [test_implementation]

  reporting_specialist:
    phases: [reporting]

quality_gates:
  - name: "Code Compilation"
    command: "mvn compile"
    required: true

  - name: "Code Style Check"
    command: "mvn checkstyle:check"
    required: true

  - name: "Test Execution"
    command: "mvn test"
    required: false

  - name: "Report Generation"
    command: "mvn allure:report"
    required: false