name: Test Password Recovery Only

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  password-recovery-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    name: "Password Recovery Tests - Validation"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install dependencies
      run: mvn dependency:resolve

    - name: Run Password Recovery tests
      id: test-execution
      continue-on-error: true
      run: |
        mvn clean test -Pci \
          -Dtest=tests.authentication.PasswordRecoveryTests \
          -Dbrowser=chrome \
          -Dheadless=true
      env:
        MAVEN_OPTS: "-Xmx2g -Xms512m"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: password-recovery-test-results
        path: |
          target/surefire-reports/
          target/screenshots/
        retention-days: 7

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: "Password Recovery Test Results"
        path: target/surefire-reports/TEST-*.xml
        reporter: java-junit
        fail-on-error: true

    - name: Fail job if tests failed
      if: steps.test-execution.outcome == 'failure'
      run: exit 1
